version: 2
updates:
  # Enable version updates for Dart/Flutter
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
    reviewers:
      - "Aorus"  # Replace with your GitHub username
    assignees:
      - "Aorus"  # Replace with your GitHub username
    labels:
      - "dependencies"
      - "dart"
      - "flutter"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
