include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
  errors:
    # RegExp deprecation warning is a Dart SDK bug (github.com/dart-lang/sdk/issues/62012)
    # The warning targets people extending/implementing RegExp, not normal usage.
    # Normal RegExp usage is correct and will continue to work.
    deprecated_member_use: ignore
    # Tests in lib/ use dev_dependencies - this is intentional for VSA
    depend_on_referenced_packages: ignore